<?php

/**
 * AssessmentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssessmentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssessmentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Assessments');
    }
    
    public static function getAllAssessments(){
        return Doctrine_Query::create()
                ->select('a.*')
                ->from('Assessments a')
                ->where('a.deleted=0')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
}