<?php

/**
 * BenefitsGrammaticalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BenefitsGrammaticalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BenefitsGrammaticalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BenefitsGrammatical');
    }
}