<?php

/**
 * DifficultyLevelsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DifficultyLevelsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DifficultyLevelsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DifficultyLevels');
    }     
    
    public static function getAllDifficultyLevels(){
        return Doctrine_Query::create()
                ->select('qdl.*')
                ->from('DifficultyLevels qdl')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
}