<?php

/**
 * LookupAcademicYears
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LookupAcademicYears extends BaseLookupAcademicYears
{
    public function getAcademicYears($grade_id){
        return Doctrine_Query::create()
                ->select('y.*')
                ->from('LookupAcademicYears y')
                ->where('y.grade_id =?', $grade_id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
}