<?php

/**
 * PagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pages');
    }
}