<?php

/**
 * Questions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Questions extends BaseQuestions
{
    public function addMultipleChoicesQuestion(array $data){
        $question_id = $this->addQuestion($data);
        
        $answer = array();
        $answer['question_id'] = $question_id;
        $answer['answer_text'] = $data['answer_text'];
        $answer['correct_answer'] = $data['correct_answer'];
        $answer['feedback'] = $data['feedback'];
        $answer['interest_grammatical'] = $data['interest_grammatical'];
        
        $qa = new QuestionAnswers();
        $qa->addQuestionAnswer($answer);
    }
    
    public function addDragAndDropQuestion(array $data){        
        $question_id = $this->addQuestion($data);
        $answer = array();
        $answer['question_id'] = $question_id;
        $answer['answer_text'] = $data['answer_text'];
        $answer['correct_answer'] = $data['answer_text'];
        $answer['feedback'] = $data['feedback'];
        $answer['interest_grammatical'] = $data['interest_grammatical'];
        
        $qa = new QuestionAnswers();
        $qa->addQuestionAnswer($answer);
    }
    
    private function addQuestion(array $data){
         $q = new Questions();
        $q->assessment_id = $data['assessment_id'];
        $q->question = $data['question'];
        $q->is_active = true;
        $q->type_id = $data['type_id'];
        $q->difficulty_level = $data['difficulty_level'];
        $q->created_at = date('ymdHis');
        $q->save();
        
        return $q->id;
    }
}