<?php

/**
 * QuestionTypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuestionTypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuestionTypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuestionTypes');
    }
    
    public static function getAllQuestionTypes(){
        return Doctrine_Query::create()
                ->select('qt.*')
                ->from('QuestionTypes qt')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
}