<?php

/**
 * QuestionAnswers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class QuestionAnswers extends BaseQuestionAnswers
{
    public function addQuestionAnswer(array $data){
        $qa = new QuestionAnswers();
        $qa->question_id = $data['question_id'];
        $qa->answer_text = $data['answer_text'];
        $qa->correct_answer = $data['correct_answer'];
        $qa->feedback = $data['feedback'];
        $qa->interest_grammatical = $data['interest_grammatical'];
        $qa->created_at = date('ymdHis');
        $qa->save();
    }
}