<?php

/**
 * QuestionAnswersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuestionAnswersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuestionAnswersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuestionAnswers');
    }
}