<?php

/**
 * UserAssessmentAnswersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserAssessmentAnswersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserAssessmentAnswersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserAssessmentAnswers');
    }
}