<?php

/**
 * UserAssessmentAnswers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserAssessmentAnswers extends BaseUserAssessmentAnswers
{
    public function addUserAnswer(array $data){
        $aa = new UserAssessmentAnswers();
        $aa->user_assessment_id = $data['user_assessment_id'];
        $aa->questions_id = $data['questions_id'];
        $aa->user_answer = $data['user_answer'];
        $aa->correct_answer = $data['correct_answer'];
        $aa->save();
    }
}