<?php

/**
 * UserAssessmentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserAssessmentsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object UserAssessmentsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('UserAssessments');
    }

    public static function getAllUserAssessments($user_id, $completed = false, $type = 2) {
        $q = Doctrine_Query::create()
                ->select('ua.id, ua.assessment_id, ua.completed, a.name')
                ->from('UserAssessments ua, ua.Assessments a')
                ->where('ua.deleted=0')
                ->andWhere('a.deleted=0');
        if ($completed) {
            $q = $q->andWhere('ua.completed=0');
        } else {
            $q = $q->andWhere('ua.completed=1');
        }
        $q = $q->andWhere('a.published=1')
                ->andWhere('ua.userid=?', $user_id)
                ->andWhere('ua.assessment_type=?', $type)
                ->orderBy('ua.created_at ASC')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
        return $q;
    }

    public static function getAssessment($user_id, $type = 2) {
        return Doctrine_Query::create()
                        ->select('ua.id, ua.assessment_id, a.name, a.description,
                    (SELECT COUNT(q.id) FROM Questions q WHERE q.assessment_id=a.id AND q.deleted=0) AS assessment_question')
                        ->from('UserAssessments ua, ua.Assessments a')
                        ->where('ua.deleted=0')
                        ->andWhere('ua.completed=0')
                        ->andWhere('a.deleted=0')
                        ->andWhere('a.published=1')
                        ->andWhere('ua.userid=?', $user_id)
                        ->andWhere('ua.assessment_type=?', $type)
                        ->orderBy('ua.created_at ASC')
                        ->limit(1)
                        ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                        ->fetchOne();
    }

    public static function isAllAssessmentCompleted($user_id, $type = 2) {
        $q = Doctrine_Query::create()
                ->select('COUNT(ua.completed) as taken')
                ->from('UserAssessments ua, ua.Assessments a')
                ->where('ua.completed =0')
                ->andWhere('ua.userid =?', $user_id)
                ->andWhere('ua.assessment_type =?', $type)
                ->andWhere('ua.deleted =0')
                ->andWhere('a.deleted =0')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->fetchOne();

        if ($q['taken'] == 0)
            return true;
        return false;
    }

    public static function getAssessmentByName($keyword = '') {
        return Doctrine_Query::create()
                        ->select('a.name, a.id')
                        ->from('Assessments a')
                        ->where('a.name LIKE ?', '%' . $keyword . '%')
                        ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                        ->execute();
    }

    public function getExamResults($assessment_id, $assessment_type = 1) { // Exams selected by type 1
        $q = Doctrine_Query::create()
                ->select('ua.id, ua.created_at, a.*, uaa.*, q.*')
                ->from('UserAssessments ua, ua.Assessments a, ua.UserAssessmentAnswers uaa')
                ->where('ua.assessment_id =?', $assessment_id)
                ->andWhere('ua.completed =1')
                ->andWhere('ua.assessment_type =?', $assessment_type)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->orderBy('ua.created_at DESC')
                ->execute();

        return $q;
    }

    public static function getAllUserExcericesOrTests($user_id, $completed = false, $type = 2) {
        $q = Doctrine_Query::create()
                ->select('a.id, a.name, ua.id, ua.completed')
                ->from('Assessments a, a.UserAssessments ua')
                ->where('ua.deleted=0')
                ->andWhere('a.deleted=0');
        if ($completed) {
            $q = $q->andWhere('ua.completed=0');
        } else {
            $q = $q->andWhere('ua.completed=1');
        }
        $q = $q->andWhere('a.published=1')
                ->andWhere('ua.userid=?', $user_id)
                ->andWhere('ua.assessment_type=?', $type)
                ->orderBy('ua.created_at ASC')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
        return $q;
    }

    public static function deleteUserAssessment($assessment_id) {
        Doctrine_Query::create()
                ->delete('UserAssessments ua')
                ->where('ua.id =?', $assessment_id)
                ->execute();
    }

}