<?php

/**
 * Users
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Users extends BaseUsers
{
    public function addUser(array $data){
        $academic_year = 1;
        if(isset($data['academic_year'])){
            $academic_year = $data['academic_year'];
        }
        
        $specialization = '';
        if(isset($data['specialization'])){
            $specialization = $data['specialization'];
        }
        
        $u = new Users();
        $u->name = $data['name'];
        $u->email = $data['email'];
        $u->password = md5($data['password']);
        $u->grade_id = $data['grade_id'];
        $u->academic_year = $academic_year;
        $u->specialization = $specialization;
        $u->confirmation_code = $data['confirmation_code'];
        $u->created_at = date('ymdHis');
        $u->save();
    }
}